In [1]:
import numpy as np

In [2]:
alist = [1,34,5,54,55]

In [3]:
arr = np.array(alist)

In [4]:
print(arr)

[ 1 34  5 54 55]


In [5]:
arr.max()

55

In [6]:
arr.mean()

29.8

In [ ]:
# vector addition
v1 = np.array([1,8])
v2 = np.array([9,9])
v3 = v1 + v2
print(v3)

In [ ]:
# multiplying scalar to a vector
print(v3*2)

In [ ]:
# dot product
v3 = v1*v2
print(v3)

In [36]:
import matplotlib.pyplot as plt

# linspace, will create a dummy dataset e^4 
x = np.linspace(0,np.e**4,50)


ModuleNotFoundError: No module named 'matplotlib'

In [10]:
y=np.log(x)


<ipython-input-10-f74e3f4aaf04>:1: RuntimeWarning: divide by zero encountered in log
  y=np.log(x)


In [2]:
plt.plot(y)


NameError: name 'plt' is not defined

In [4]:
import numpy as np

In [8]:
array = np.array([12,3,44,55,55,33])

In [10]:
print(array)

[12  3 44 55 55 33]


In [12]:
print(np.max(array))

55


In [14]:
alist = [12,45,4,54,445]
print(np.array(alist,float))

[ 12.  45.   4.  54. 445.]


In [17]:
v1 = np.array([12,34])
v2 = np.array([23,45])
v3 = v1 + v2 

In [18]:
print(v3)

[35 79]


In [19]:
print(3*v3)

[105 237]


In [35]:
blist = [12,38,33,22]
print(3*[np.array(blist)])

[array([12, 38, 33, 22]), array([12, 38, 33, 22]), array([12, 38, 33, 22])]
